---
title: "Ejemplo código Análisi de comunidades"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(vegan)
library(BiodiversityR)
```
Base de datos
```{r}
mosquitos
mosquitos.tabla <- ftable(SITIO ~ ESPECIE,data = mosquitos)
```


EJEMPLO DE CÓDIGO
```{r}
library(BiodiversityR)
library(vegan)
#BASE DE DATOS
pd <- read.csv("Plant species errors fixed.csv",header = T)
#Formar una tabla
pd.t <- ftable(Site ~Species,data = pd)
#Medir Riqueza
colSums(pd.t)
#Pedir los nombres de las columnas
levels(pd$Site)
s <- specnumber(t(pd.t),)
names(s) <- levels(pd$Site)

#Nueva base de datos
gb.biol <- read.csv("Ground Beetles and abundance.csv",row.names = 1)
dim(gb.biol)
range(rowSums(gb.biol))
rarefy(gb.biol,sample = 205)
drarefy(gb.biol,sample = 205)

### CURVA DE ACUMULACIÓN DE ESPECIES ###
gb.sa <- specaccum(gb.biol,method = "collector")
gb.sa$richness

plot(gb.sa)

gb.site <- read.csv("GBsite.csv",row.names=1)

head(gb.site)

ac <- accumcomp(x = gb.biol,y=gb.site,factor = "Habitat", 
                plotit = T, rainbow = F,legend = F, xlim = c(0,7))

gb.sa2 <- as.data.frame(gb.sa)

###Estimacion de Riqueza ###
library(fossil)
est <- spp.est(t(gb.biol),rand=100, abund = T)
gb.site
library(ggplot2)
edge.sp <- data.frame(spp.est(t(gb.site),rand = 100, abund = T), 
                      Acumulacion = edge.ac$richeness, 
                      Habitat = rep("Edge",nrow(gb.edge))plot=T)

ggplot(gb.sa,aes(gb.sa$richeness,)) +geom_point() 
   + facet_wrap(~Habitat)

ac <- accumcomp(x = gb.biol,y=gb.site,factor = "Habitat", 
                plotit = T, rainbow = F,legend = F, xlim = c(0,7))


### Curvas de Rango de Abundancia ###

# 1.- Estandarizar matriz
gb.biol
gb.ra <- rrarefy(gb.biol,sample = 205)

#Rangos de abundancia
gb.rank <- rankabundance(gb.biol)
gb.rank <- rankabundance(gb.biol)

diversity (gb.biol,index = "shannon")

#JACCARD
gb.j <- betadiver(gb.biol,"j")

#representar denogrmas (matriz de distancia de los indices de jjaccard)
plot(hclust(gb.j),hang=-1)

#graficar valores inversos (en función de lo que se parece)
plot(hclust(1-gb.j),hang=-1)

#Suma de fila por Habitat
gbt <- rowsum(gb.biol,group= gb.site$Habitat)
gbt [1:8]

#calcular diversidad
gb.j <- betadiver(gbt, "j")
plot(hclust(1-gb.j),hang=-1)

###DIVERSIDAD BETA
library(betapart)
gb.tp <- gbt
gb.biol[gb.biol>0]<-1
gb.biol[,1:8]
beta.multi(gb.biol,index.family = "sorense")

#explorar elementos de la b. diversidad , calcula por tipo de habitat
beta.pair(gb.biol,index.family = "sorensen")


```


EJEMPLO 2 de código
```{r}
### Grafica de  curva de acumulación , PRACTICA ##


#Librerias
library(BiodiversityR)
library(vegan)
library(fossil)
library(ggplot2)
library(dplyr)
library(tidyverse)


gb.biol <- read.csv("Ground Beetles and abundance.csv",row.names = 1)

# 1.- Filtra base de datos gb.biol
E <- gb.biol [1:6,]
G <- gb.biol [7:12,]
W <- gb.biol[13:18,]

# 2.- sacar Riqueza
E.ac <- specaccum(E, method = "collector")
G.ac <- specaccum(G, method = "collector")
W.ac <- specaccum(W, method = "collector")

# 3.- Sacar acumulación
E.est <- spp.est(t(E), rand = 100, abund = T)
G.est <- spp.est(t(G), rand = 100, abund = T)
W.est <- spp.est(t(W), rand = 100, abund = T)

# 4.- pegar las bases de datos
df <- rbind(E.est, G.est, W.est)
df <- as.data.frame(df)
df <- cbind(df,gb.site$Habitat)

# 5.- seleccionar base de datos
df2 <- df %>% select (N.obs, S.obs,  Chao1,  Jack1 ,`gb.site$Habitat`)%>% gather("variable", "valor",2:4)
# 6.- Graficar

ggplot(df2,aes(N.obs,valor,group=variable,col=variable,lty=variable)) + geom_line()+ facet_wrap(~gb.site$Habitat)
```


```{r}
#Medir Riqueza
colSums(mosquitos.tabla)

#Pedir los nombres de las columnas
s <- specnumber(t(mosquitos.tabla),)
s.names <- names(s) <- levels(mosquitos$SITIO)
s.mosquits <- specaccum(mosquitos,method = "collector")
```


```{r}
gb.biol <- read.csv("Ground Beetles and abundance.csv",row.names = 1)
dim(gb.biol)
range(rowSums(gb.biol))
rarefy(gb.biol,sample = 205)
drarefy(gb.biol,sample = 205)
# CURVA DE ACUMULACIÓN DE ESPECIES
gb.sa <- specaccum(gb.biol,method = "collector")
gb.sa
gb.sa$richness
plot(gb.sa)
gb.site <- read.csv("GBsite.csv",row.names=1)
head(gb.site)
ac <- accumcomp(x = gb.biol,y=gb.site,factor = "Habitat", plotit = T, rainbow = F,legend = F, xlim = c(0,7))
ac
gb.sa2 <- as.data.frame(gb.sa)
```

```{r}

mosquitos.1 <- mosquitos %>% select(SITIO,TRAMPA,GENERO,ESPECIE,NOMBRE,SEXO,EDAD)

rarefy(gb.biol,sample = 205)
drarefy(gb.biol,sample = 205)

# CURVA DE ACUMULACIÓN DE ESPECIES

mosquitos.1 <- specaccum(mosquitos,method = "random")
gb.sa
gb.sa$richness
plot(gb.sa)
gb.site <- read.csv("GBsite.csv",row.names=1)
head(gb.site)
ac <- accumcomp(x = gb.biol,y=gb.site,factor = "Habitat", plotit = T, rainbow = F,legend = F, xlim = c(0,7))
ac
gb.sa2 <- as.data.frame(gb.sa)
```
Código con base de datos Mosquitos
```{r}
mosquitos.1
S <- specnumber(mosquitos.1)
(raremax <- min(rowSums(mosquitos.1)))
```

